List<String> getLyrics() {
  return [
    'When the night comes',
    'And you dont know which way to go',
    'Through the shadowlands',
    'And forgotten paths',
    'You will find a road',
    'Like an owl you must fly in moonlight with an open eye',
    'And use your instinct as your guide',
    'To navigate the ways that lays before you',
    'You were born to, take the greatest flight',
    'Like a serpent and a dove, you will have wisdom born of love',
    'And carry visions from above into the places no man dares to follow',
    'Every hollow in the dark of night',
    'Waiting for the light',
    'Take the flame tonight',
    'Cause child the time has come for you to go',
    'You will never be alone',
    'Every dream that you have been shown',
    'Will be like living stone',
    'Building you into a home',
    'A shelter from the storm',
    'Like a messenger of peace, the beauty waits to be released',
    'Upon the sacred path you keep, leading deeper into the unveiling',
    'As your sailing, across the great divide',
    'Like a wolf at midnight howls, you use your voice in darkest hours',
    'To break the silence and the power,',
    'Holding back the others from their glory',
    'Every story will be written soon',
    'The blood is on the moon',
    'Morning will come soon',
    'Cause child the time has come for you to go',
    'You will never be alone',
    '  Every dream that you have been shown',
    'Will be like living stone',
    'Building you into a home',
    'A shelter from the storm'
  ];
}
